# Generated by Django 3.1 on 2023-05-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_holidaysetting_user'),
        ('authentication', '0002_timeoffsetting_balance_recorded_date'),
    ]

    operations = [
    ]
