# Generated by Django 3.1 on 2023-05-22 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20230521_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaysetting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BookedDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time_off_type', models.CharField(choices=[('pto', ''), ('holidays', ''), ('sick_days', '')], default='pto', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
