# Generated by Django 3.1.5 on 2023-05-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_subscriptions'),
        ('authentication', '0006_auto_20230504_1457'),
    ]

    operations = [
    ]
