# Generated by Django 3.1.5 on 2023-05-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230510_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffsetting',
            old_name='policy_types',
            new_name='policy_type',
        ),
    ]
