# Generated by Django 3.1.5 on 2023-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20230511_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
