# Generated by Django 3.1.5 on 2023-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_holidaysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaysetting',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
