# Generated by Django 3.1.5 on 2023-05-01 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_off_type', models.CharField(choices=[('pto', ''), ('holidays', ''), ('sick_days', '')], default='pto', max_length=100)),
                ('accrual_type', models.CharField(choices=[('accrual', ''), ('lump_sump', ''), ('unlimited', '')], default='accrual', max_length=100)),
                ('annual_allowance_days', models.IntegerField(null=True)),
                ('accrual_cap_days', models.IntegerField(null=True)),
                ('current_balance_days', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
