# Generated by Django 3.1.5 on 2023-05-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_timeoffsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeOffSettings',
            new_name='TimeOffSetting',
        ),
    ]
