# Generated by Django 3.1.5 on 2023-05-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230501_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffsetting',
            old_name='user_id',
            new_name='user',
        ),
    ]
