# Generated by Django 3.1.5 on 2023-05-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_20230508_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffsetting',
            old_name='accrual_type',
            new_name='policy_types',
        ),
    ]
