# Generated by Django 3.1 on 2023-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffsetting',
            name='accrual_cap_days',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='timeoffsetting',
            name='annual_allowance_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='timeoffsetting',
            name='current_balance_days',
            field=models.IntegerField(default=7),
        ),
    ]
